In [1]:
import tensorflow as tf 
from tensorflow import keras 
import numpy as np
from tensorflow.keras import layers 
from tensorflow.keras.datasets import mnist 


In [2]:
# A tensor is an n dimensional array of data 
#vector is 1D tensor and matrix is 2D tensor 

In [3]:
# initialization 
x=tf.constant(4)
print(x)
x1=tf.constant(4, shape=(1,1), dtype=tf.float32) 
print(x1)
x2=tf.constant([[1,2,3],[4,5,6]])
print(x2)
x3=tf.ones((3,3))
print(x3)
x4=tf.eye(3)
print(x4)
x5=tf.random.normal((3,3), mean=0, stddev=1) # to get normal distribution with mean =0, and standard dev=1, for uniform
# distribution use tf.random.uniform((1,3), minval=0, maxval=1)
print(x5)
x6=tf.range(start=1, limit=10, delta=2) # delta is same as step
print(x6)
#x=tf.caast(x, dtype=tf.float64), tf.bool (casting in boolean)

x=tf.constant([1,2,3])
y=tf.constant([9,8,7])
z=tf.add(x,y) # or z=x+, x-y, x/y, x*y

z=tf.tensordot(x,y,axes=1)
print(z)
z=tf.reduce_sum(x*y, axis=0)
print(z)
z=x**5 
print(z)

x=tf.random.normal((2,3))
y=tf.random.normal((3,4))
z=tf.matmul(x,y)
print(z)
print(x@y)
x=tf.constant([0,1,2,3,4,5,6])
print(x[::-1]) # will print x in reverse order 
indices=tf.constant([0,3])
x_ind=tf.gather(x,indices)

x=tf.constant([[1,2],
             [3,4],
             [5,6]])
print(x[0,:])
print(x[0:2,:])
# indexing is same as python 

x=tf.range(9)
print(x)
x=tf.reshape(x,(3,3))
print(x)
x=tf.transpose(x, perm=[1,0]) # inverse the axis 
print(x)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([[4.]], shape=(1, 1), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 0.515029   -0.649522    1.1850352 ]
 [-1.5125637   1.5492306   0.38609573]
 [ 0.05778437  1.0206742  -0.81093514]], shape=(3, 3), dtype=float32)
tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)
tf.Tensor(46, shape=(), dtype=int32)
tf.Tensor(46, shape=(), dtype=int32)
tf.Tensor([  1  32 243], shape=(3,), dtype=int32)
tf.Tensor(
[[  5.425405    -0.80187505   1.2159604    0.3933717 ]
 [-11.669405     3.601153    -0.39957464  -2.1973329 ]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[  5.425405    -0.80187505   1.2159604    0.3933717 ]
 [-11.669405     3.601153    -0.39957464  -2.1973329 ]], shape=(2, 4), dtype=float32)
tf.Tensor([6 5 4 3 2 1 0], shape=(7,), dtype=int32)
tf.Tensor([1 2],

In [4]:
(x_train, y_train),(x_test, y_test)=mnist.load_data()
print(x_train.shape)
print(y_train.shape)
# here we flatten our data 
# and when we flatten we dont need to specify the input  in keras 
x_train= x_train.reshape(-1, 28*28).astype("float32")/255.0
print(x_train.shape)
x_test= x_test.reshape(-1, 28*28).astype("float32")/ 255.0
print(x_test.shape)


(60000, 28, 28)
(60000,)
(60000, 784)
(10000, 784)


In [5]:
# sequential api (only one input to one output mapping)
# if we want to use model.summary then we have to provide keras.input 
# else we can use model.summary after fitting 
# model=keras.Sequential([
#     keras.Input(shape=(28*28)),
#     layers.Dense(512, activation='relu'),# fully connected layer
#     layers.Dense(256, activation='relu'),
#     layers.Dense(10),
#     ]
# )

#or
model=keras.Sequential()
model.add(keras.Input(shape=(784)))
model.add(layers.Dense(512, activation ='relu'))
print(model.summary())
model.add(layers.Dense(256,activation='relu'))
model.add(layers.Dense(10))

print(model.summary())


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 512)               401920    
                                                                 
Total params: 401,920
Trainable params: 401,920
Non-trainable params: 0
_________________________________________________________________
None
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 512)               401920    
                                                                 
 dense_1 (Dense)             (None, 256)               131328    
                                                                 
 dense_2 (Dense)             (None, 10)                2570      
                                                                 
Total params: 535,818
Tra

In [6]:
# this is the step of how to debug betwen the layers or taking output after the 
# desired layer 

model=keras.Model(inputs=model.inputs, outputs=[model.layers[-2].output]) # for second last layer 
#model=keras.Model(inputs=model.inputs, outputs=[layer.output for layer in model.layers]
# to get output from all of the layers 
feature=model.predict(x_train)
print(feature.shape)

(60000, 256)


In [7]:
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(lr=0.001),
    metrics=["accuracy"], )

 # as we didnt passes the softmax fun at last layer from_logits gonna
#handle that 
# lr=learning rate

model.fit(x_train, y_train, batch_size=32, epochs=5, verbose=2) #verbose print result after ephocs
model.evaluate(x_test,y_test,  verbose=2)

Epoch 1/5


C:\Users\msi1\anaconda3\lib\site-packages\keras\optimizer_v2\adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


1875/1875 - 10s - loss: 1.9606 - accuracy: 0.6894 - 10s/epoch - 6ms/step
Epoch 2/5
1875/1875 - 11s - loss: 1.8127 - accuracy: 0.7442 - 11s/epoch - 6ms/step
Epoch 3/5
1875/1875 - 10s - loss: 1.7799 - accuracy: 0.7566 - 10s/epoch - 5ms/step
Epoch 4/5
1875/1875 - 11s - loss: 1.7627 - accuracy: 0.7661 - 11s/epoch - 6ms/step
Epoch 5/5
1875/1875 - 12s - loss: 1.7522 - accuracy: 0.7709 - 12s/epoch - 6ms/step
313/313 - 2s - loss: 1.8200 - accuracy: 0.7545 - 2s/epoch - 5ms/step


[1.8200291395187378, 0.7544999718666077]

In [8]:
# sequential api can only handle one input to one output so here we go for 
#functional api (more flexible)

inputs=keras.Input(shape=(784))
x=layers.Dense(512, activation='relu')(inputs)
x=layers.Dense(256, activation= 'relu')(x)
outputs = layers.Dense(10,activation='softmax')(x)
model=keras.Model(inputs=inputs, outputs=outputs)
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    optimizer=keras.optimizers.Adam(lr=0.001),
    metrics=["accuracy"], )
model.fit(x_train, y_train, batch_size=32, epochs=5, verbose=2) #verbose print result after ephocs
model.evaluate(x_test,y_test,  verbose=2)

Epoch 1/5
1875/1875 - 10s - loss: 0.1886 - accuracy: 0.9427 - 10s/epoch - 5ms/step
Epoch 2/5
1875/1875 - 11s - loss: 0.0805 - accuracy: 0.9747 - 11s/epoch - 6ms/step
Epoch 3/5
1875/1875 - 11s - loss: 0.0542 - accuracy: 0.9830 - 11s/epoch - 6ms/step
Epoch 4/5
1875/1875 - 11s - loss: 0.0436 - accuracy: 0.9861 - 11s/epoch - 6ms/step
Epoch 5/5
1875/1875 - 11s - loss: 0.0349 - accuracy: 0.9885 - 11s/epoch - 6ms/step
313/313 - 1s - loss: 0.0825 - accuracy: 0.9761 - 1s/epoch - 4ms/step


[0.08247809112071991, 0.9761000275611877]

In [9]:
#we can use optimizers other than Adam like Gradient Descent with momentum, Adagrad, and RMSprop

# 

In [10]:
# working with cifar dataset 
#50000 test, 10000, 32*32 pixels rgb 
from tensorflow.keras.datasets import cifar10

In [32]:
(x_train, y_train),(x_test,y_test)= cifar10.load_data()
x_train=x_train.astype("float32")/255.0
x_test= x_test.astype("float32")/ 255.0
model= keras.Sequential(
   [
       keras.Input(shape=(32,32,3)),# as we havent flatten it so we maintain the input shape 
       layers.Conv2D(32,3,padding='valid', activation='relu'), # it is default padding='valid'
       # here 32 is the no. of filters, and 3 is the kernal size(3,3), padding can be valid or same
       # in same padding output pixel is not going to change while in valid it would change 
       
       layers.MaxPooling2D(pool_size=(2,2)),
       #(2,2) pooling will make it half 
       layers.Conv2D(64,3,activation='relu'),
       layers.MaxPooling2D(),
       layers.Conv2D(128,3,activation='relu'),
       layers.Flatten(),
       layers.Dense(64,activation='relu'),
       layers.Dense(10),
   ]
)
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_6 (Conv2D)           (None, 30, 30, 32)        896       
                                                                 
 max_pooling2d_4 (MaxPooling  (None, 15, 15, 32)       0         
 2D)                                                             
                                                                 
 conv2d_7 (Conv2D)           (None, 13, 13, 64)        18496     
                                                                 
 max_pooling2d_5 (MaxPooling  (None, 6, 6, 64)         0         
 2D)                                                             
                                                                 
 conv2d_8 (Conv2D)           (None, 4, 4, 128)         73856     
                                                                 
 flatten_2 (Flatten)         (None, 2048)             

In [33]:
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(lr=3e-4)
)
model.fit(x_train, y_train, batch_size=64, epochs=10, verbose=2)

Epoch 1/10
782/782 - 32s - loss: 1.6785 - 32s/epoch - 41ms/step
Epoch 2/10
782/782 - 33s - loss: 1.3551 - 33s/epoch - 43ms/step
Epoch 3/10
782/782 - 35s - loss: 1.2177 - 35s/epoch - 45ms/step
Epoch 4/10
782/782 - 37s - loss: 1.1157 - 37s/epoch - 47ms/step
Epoch 5/10
782/782 - 38s - loss: 1.0407 - 38s/epoch - 49ms/step
Epoch 6/10
782/782 - 34s - loss: 0.9804 - 34s/epoch - 44ms/step
Epoch 7/10
782/782 - 34s - loss: 0.9286 - 34s/epoch - 43ms/step
Epoch 8/10
782/782 - 34s - loss: 0.8785 - 34s/epoch - 44ms/step
Epoch 9/10
782/782 - 34s - loss: 0.8375 - 34s/epoch - 43ms/step
Epoch 10/10
782/782 - 37s - loss: 0.7963 - 37s/epoch - 47ms/step


In [31]:
x_train.shape

(50000, 32, 32, 3)

In [27]:
y_train.shape

(10000, 32, 32, 3)

In [28]:
x_test.shape

(50000, 1)