In [2]:
import pandas as pd
import numpy as np
import random
import csv
import matplotlib.pyplot as plt


In [9]:
import numpy as np
import random
# let m= training example, n= number of features 
# dims of y=(1,m), X =(n,m), w(n,1)
class LinearReg():
    def __init__(self):
        self.learning_rate=0.01
        self.total_iterations=10000
        
    def y_hat(self,x,w):
        return np.dot(w.T,x)
    
    def loss(self,yhat, y):# yhat= w1x1+ w2x2 +.....
        L=  (1/self.m)* np.sum(np.power(yhat-y, 2))
        #L=np.sum((y - yhat) ** 2) / len(y)
        return L
    
    def gradient_descent(self, w, x, y, yhat):
        #shape y =(1,m), x is (n,m)
        # output should be (n,1)
        
        dldw= 2/self.m * np.dot(x, (yhat-y).T)
        w=w - self.learning_rate*dldw
        return w
         
    def main(self,x,y):
        # here we have also considered x1 for all training examples so we need to
        #add 1 to all training example i.e we have to add one more input vector all columns 
        
        
        x1=np.ones((1, x.shape[1]))
        x= np.append(x, x1, axis=0)
        
        self.m= x.shape[1]
        self.n= x.shape[0]
        
        w=np.zeros((self.n, 1))
        
        for i in range(self.total_iterations +1):
            
    
            yhat= self.y_hat(x,w)
            loss= self.loss(yhat,y)

            if i%100 ==0:
                print(f'cost of iterations {i} is {loss}')
            w=self.gradient_descent(w,x,y,yhat)
        return w
if __name__=='__main__':
    x=np.random.randn(1,500)
   
    y=3*x + np.random.randn(1,500)*0.1
    regression= LinearReg()
    w= regression.main(x,y)

cost of iterations 0 is 10.171270363520565
cost of iterations 100 is 0.11637805046842217
cost of iterations 200 is 0.011567393160068622
cost of iterations 300 is 0.010400300786542964
cost of iterations 400 is 0.010386012253213608
cost of iterations 500 is 0.010385816341750488
cost of iterations 600 is 0.01038581334591619
cost of iterations 700 is 0.010385813296022967
cost of iterations 800 is 0.010385813295143802
cost of iterations 900 is 0.010385813295127782
cost of iterations 1000 is 0.010385813295127486
cost of iterations 1100 is 0.010385813295127482
cost of iterations 1200 is 0.01038581329512748
cost of iterations 1300 is 0.010385813295127479
cost of iterations 1400 is 0.010385813295127479
cost of iterations 1500 is 0.01038581329512748
cost of iterations 1600 is 0.010385813295127482
cost of iterations 1700 is 0.010385813295127484
cost of iterations 1800 is 0.010385813295127484
cost of iterations 1900 is 0.010385813295127484
cost of iterations 2000 is 0.010385813295127484
cost of it

In [10]:
x

array([[ 6.69181573e-01, -4.41875050e-01,  1.89245754e-01,
         2.28022794e-01,  4.18204236e-01, -9.67693921e-01,
        -6.37846818e-01,  2.28506568e-01,  3.28407048e-01,
         9.11853781e-01,  1.37956524e+00,  3.03414413e-01,
         3.25790485e-01,  8.80432825e-01,  9.96963048e-01,
        -1.19994544e-01,  1.99301273e+00,  2.19037081e-01,
        -1.00938222e+00, -1.46381949e+00, -1.34442798e+00,
         5.69708212e-01,  1.52954724e+00, -4.72390133e-01,
         7.72331491e-01,  1.04334155e+00, -6.42808374e-01,
        -2.92771640e-02,  4.02887104e-01, -5.98246884e-02,
        -5.32247248e-01,  1.39079331e+00, -1.17554466e+00,
        -2.02443356e+00,  1.15967768e+00, -1.97157627e+00,
         5.30572455e-01, -1.03310651e+00, -1.30031190e+00,
        -1.23117202e-01, -1.16337753e+00, -1.12327144e+00,
        -1.31181140e+00,  9.27422902e-01,  2.39320038e-01,
         9.96844032e-01, -1.43533435e+00,  1.14268503e+00,
        -6.95906663e-01,  7.40315200e-01, -1.87160954e-0

In [11]:
y =x

In [12]:
y=y.tolist()

In [13]:
for i in y:
    i.insert(0,1)
y=np.array(y)
y

array([[ 1.00000000e+00,  6.69181573e-01, -4.41875050e-01,
         1.89245754e-01,  2.28022794e-01,  4.18204236e-01,
        -9.67693921e-01, -6.37846818e-01,  2.28506568e-01,
         3.28407048e-01,  9.11853781e-01,  1.37956524e+00,
         3.03414413e-01,  3.25790485e-01,  8.80432825e-01,
         9.96963048e-01, -1.19994544e-01,  1.99301273e+00,
         2.19037081e-01, -1.00938222e+00, -1.46381949e+00,
        -1.34442798e+00,  5.69708212e-01,  1.52954724e+00,
        -4.72390133e-01,  7.72331491e-01,  1.04334155e+00,
        -6.42808374e-01, -2.92771640e-02,  4.02887104e-01,
        -5.98246884e-02, -5.32247248e-01,  1.39079331e+00,
        -1.17554466e+00, -2.02443356e+00,  1.15967768e+00,
        -1.97157627e+00,  5.30572455e-01, -1.03310651e+00,
        -1.30031190e+00, -1.23117202e-01, -1.16337753e+00,
        -1.12327144e+00, -1.31181140e+00,  9.27422902e-01,
         2.39320038e-01,  9.96844032e-01, -1.43533435e+00,
         1.14268503e+00, -6.95906663e-01,  7.40315200e-0

In [14]:
x=x.T 
x1=np.ones((1, x.shape[1]),dtype='int64')
x1.shape 

(1, 1)

In [15]:
result= np.concatenate((x,x1), axis=0)
result.T

array([[ 6.69181573e-01, -4.41875050e-01,  1.89245754e-01,
         2.28022794e-01,  4.18204236e-01, -9.67693921e-01,
        -6.37846818e-01,  2.28506568e-01,  3.28407048e-01,
         9.11853781e-01,  1.37956524e+00,  3.03414413e-01,
         3.25790485e-01,  8.80432825e-01,  9.96963048e-01,
        -1.19994544e-01,  1.99301273e+00,  2.19037081e-01,
        -1.00938222e+00, -1.46381949e+00, -1.34442798e+00,
         5.69708212e-01,  1.52954724e+00, -4.72390133e-01,
         7.72331491e-01,  1.04334155e+00, -6.42808374e-01,
        -2.92771640e-02,  4.02887104e-01, -5.98246884e-02,
        -5.32247248e-01,  1.39079331e+00, -1.17554466e+00,
        -2.02443356e+00,  1.15967768e+00, -1.97157627e+00,
         5.30572455e-01, -1.03310651e+00, -1.30031190e+00,
        -1.23117202e-01, -1.16337753e+00, -1.12327144e+00,
        -1.31181140e+00,  9.27422902e-01,  2.39320038e-01,
         9.96844032e-01, -1.43533435e+00,  1.14268503e+00,
        -6.95906663e-01,  7.40315200e-01, -1.87160954e-0

In [16]:
x

array([[ 6.69181573e-01],
       [-4.41875050e-01],
       [ 1.89245754e-01],
       [ 2.28022794e-01],
       [ 4.18204236e-01],
       [-9.67693921e-01],
       [-6.37846818e-01],
       [ 2.28506568e-01],
       [ 3.28407048e-01],
       [ 9.11853781e-01],
       [ 1.37956524e+00],
       [ 3.03414413e-01],
       [ 3.25790485e-01],
       [ 8.80432825e-01],
       [ 9.96963048e-01],
       [-1.19994544e-01],
       [ 1.99301273e+00],
       [ 2.19037081e-01],
       [-1.00938222e+00],
       [-1.46381949e+00],
       [-1.34442798e+00],
       [ 5.69708212e-01],
       [ 1.52954724e+00],
       [-4.72390133e-01],
       [ 7.72331491e-01],
       [ 1.04334155e+00],
       [-6.42808374e-01],
       [-2.92771640e-02],
       [ 4.02887104e-01],
       [-5.98246884e-02],
       [-5.32247248e-01],
       [ 1.39079331e+00],
       [-1.17554466e+00],
       [-2.02443356e+00],
       [ 1.15967768e+00],
       [-1.97157627e+00],
       [ 5.30572455e-01],
       [-1.03310651e+00],
       [-1.3

In [17]:
a = x
b = np.ones((1, x.shape[0]),dtype='int64')

In [18]:
c = np.concatenate((b.T,a),axis=1)
c

array([[ 1.00000000e+00,  6.69181573e-01],
       [ 1.00000000e+00, -4.41875050e-01],
       [ 1.00000000e+00,  1.89245754e-01],
       [ 1.00000000e+00,  2.28022794e-01],
       [ 1.00000000e+00,  4.18204236e-01],
       [ 1.00000000e+00, -9.67693921e-01],
       [ 1.00000000e+00, -6.37846818e-01],
       [ 1.00000000e+00,  2.28506568e-01],
       [ 1.00000000e+00,  3.28407048e-01],
       [ 1.00000000e+00,  9.11853781e-01],
       [ 1.00000000e+00,  1.37956524e+00],
       [ 1.00000000e+00,  3.03414413e-01],
       [ 1.00000000e+00,  3.25790485e-01],
       [ 1.00000000e+00,  8.80432825e-01],
       [ 1.00000000e+00,  9.96963048e-01],
       [ 1.00000000e+00, -1.19994544e-01],
       [ 1.00000000e+00,  1.99301273e+00],
       [ 1.00000000e+00,  2.19037081e-01],
       [ 1.00000000e+00, -1.00938222e+00],
       [ 1.00000000e+00, -1.46381949e+00],
       [ 1.00000000e+00, -1.34442798e+00],
       [ 1.00000000e+00,  5.69708212e-01],
       [ 1.00000000e+00,  1.52954724e+00],
       [ 1.